FROM ubuntu

#ENV JAVA_VERSION 8u31
#ENV BUILD_VERSION b13

RUN apt-get update -y
RUN apt-get install apt-utils -y
RUN apt-get upgrade -y
RUN apt-get install nano -y
RUN apt-get install -y wget
RUN apt-get install -y curl
RUN apt-get install -y maven

RUN apt-get install python-software-properties -y
RUN apt-get install apt-file -y
RUN apt-file update
RUN apt-get install software-properties-common -y

RUN add-apt-repository ppa:webupd8team/java
RUN apt-get update
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
RUN apt-get install oracle-java8-installer -y
RUN apt-get install oracle-java8-set-default -y

WORKDIR /app/ovt/

ADD maven/sfg-thymeleaf-course-0.0.1-SNAPSHOT.jar sfg-thymeleaf-course.jar

#RUN sh -c 'touch /sfg-thymeleaf-course.jar'

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/sfg-thymeleaf-course.jar"]



